from qaira_semantic_compiler.core.context import AgentResult
import json

BODY_METHODS={"POST","PUT","PATCH"}

class TestGenerationAgent:
    name="TestGenerationAgent"

    def __init__(self, ctx, logger):
        self.ctx=ctx
        self.logger=logger

    def run(self):
        contracts=self.ctx.state.get("contracts",[])
        inferred=self.ctx.state.get("inferredSchemas",[])

        components={"schemas":{}}
        for s in inferred:
            components["schemas"][s["name"]]=s["schema"]

        paths={}
        for c in contracts:
            op={
                "parameters":c["parameters"],
                "responses":{"200":{"description":"OK"}}
            }

            rb=c.get("requestBody")
            if rb:
                schema_name=rb.get("schemaRef")
                if schema_name:
                    schema={"$ref":"#/components/schemas/"+schema_name}
                else:
                    schema=rb
                op["requestBody"]={
                    "required": c["method"] in BODY_METHODS,
                    "content":{"application/json":{"schema":schema}}
                }

            paths.setdefault(c["path"],{})[c["method"].lower()]=op

        openapi={
            "openapi":"3.0.0",
            "info":{
                "title":"Generated API Contract",
                "description":"Generated by QAira semantic compiler"
            },
            "paths":paths,
            "components":components
        }
        self.ctx.write_json("generated/openapi.json",openapi)

        postman_items=[]
        negative_items=[]
        edge_items=[]

        for c in contracts:
            body_obj={}
            rb=c.get("requestBody") or {}
            props=rb.get("properties") or {}
            required=set(rb.get("required") or [])

            for k,v in props.items():
                body_obj[k]="{{data."+k+"}}"

            base_item={
                "name":f"{c['method']} {c['path']}",
                "request":{
                    "method":c["method"],
                    "url":"{{baseUrl}}"+c["path"]
                }
            }
            if body_obj:
                base_item["request"]["body"]={"mode":"raw","raw":json.dumps(body_obj)}
            postman_items.append(base_item)

            # Negative tests for missing required fields.
            for req in sorted(required):
                neg_body={k:v for k,v in body_obj.items() if k!=req}
                negative_items.append({
                    "name":f"NEG missing {req} - {c['method']} {c['path']}",
                    "request":{
                        "method":c["method"],
                        "url":"{{baseUrl}}"+c["path"],
                        "body":{"mode":"raw","raw":json.dumps(neg_body)}
                    },
                    "expectedStatus":[400,422]
                })

            # Edge test with empty strings for string-like fields.
            if body_obj and c["method"] in BODY_METHODS:
                edge_body={k:"" for k in body_obj.keys()}
                edge_items.append({
                    "name":f"EDGE empty strings - {c['method']} {c['path']}",
                    "request":{
                        "method":c["method"],
                        "url":"{{baseUrl}}"+c["path"],
                        "body":{"mode":"raw","raw":json.dumps(edge_body)}
                    },
                    "expectedStatus":[200,400,422]
                })

        self.ctx.write_json("generated/postman_collection.json",{
            "info":{"name":"Generated API Collection","schema":"https://schema.getpostman.com/json/collection/v2.1.0/collection.json"},
            "item":postman_items
        })
        self.ctx.write_json("generated/negative_tests.postman_collection.json",{
            "info":{"name":"Generated Negative API Tests","schema":"https://schema.getpostman.com/json/collection/v2.1.0/collection.json"},
            "item":negative_items
        })
        self.ctx.write_json("generated/edge_tests.postman_collection.json",{
            "info":{"name":"Generated Edge API Tests","schema":"https://schema.getpostman.com/json/collection/v2.1.0/collection.json"},
            "item":edge_items
        })

        self.ctx.write_text("generated/curl_requests.sh","\n".join([f"curl -X {c['method']} \"$BASE_URL{c['path']}\"" for c in contracts])+"\n")
        self.ctx.write_json("generated/qaira_tests.json",{"tests":postman_items,"negativeTests":negative_items,"edgeTests":edge_items})
        self.ctx.write_json("final/final_test_generation_report.json",{
            "generated":["openapi","postman","negative_postman","edge_postman","curl","qaira"],
            "contractCount":len(contracts),
            "negativeTests":len(negative_items),
            "edgeTests":len(edge_items),
            "componentSchemas":len(components["schemas"])
        })
        return AgentResult(self.name,"success",0.95 if contracts else 0,{"generated":6,"contracts":len(contracts),"negativeTests":len(negative_items),"edgeTests":len(edge_items)}, {})
