from qaira_semantic_compiler.core.context import AgentResult
import json
class TestGenerationAgent:
    name="TestGenerationAgent"
    def __init__(self, ctx, logger): self.ctx=ctx; self.logger=logger
    def run(self):
        contracts=self.ctx.state.get("contracts",[])
        paths={}
        for c in contracts:
            paths.setdefault(c["path"],{})[c["method"].lower()]={"parameters":c["parameters"],"requestBody":{"content":{"application/json":{"schema":c["requestBody"]}}} if c.get("requestBody") else None,"responses":{"200":{"description":"OK"}}}
        openapi={"openapi":"3.0.0","info":{"title":"Generated API Contract","description":"Generated by QAira semantic compiler"},"paths":paths}
        self.ctx.write_json("generated/openapi.json",openapi)
        items=[]
        for c in contracts:
            items.append({"name":f"{c['method']} {c['path']}","request":{"method":c["method"],"url":"{{baseUrl}}"+c["path"],"body":{"mode":"raw","raw":json.dumps({k:"{{data."+k+"}}" for k in ((c.get("requestBody") or {}).get("properties") or {}).keys()})}}})
        self.ctx.write_json("generated/postman_collection.json",{"info":{"name":"Generated API Collection","schema":"https://schema.getpostman.com/json/collection/v2.1.0/collection.json"},"item":items})
        self.ctx.write_text("generated/curl_requests.sh","\n".join([f"curl -X {c['method']} \"$BASE_URL{c['path']}\"" for c in contracts])+"\n")
        self.ctx.write_json("generated/qaira_tests.json",{"tests":items})
        self.ctx.write_json("final/final_test_generation_report.json",{"generated":["openapi","postman","curl","qaira"],"contractCount":len(contracts)})
        return AgentResult(self.name,"success",0.95 if contracts else 0,{"generated":4,"contracts":len(contracts)}, {})
