from qaira_semantic_compiler.core.context import AgentResult
import json

BODY_METHODS={"POST","PUT","PATCH"}

class TestGenerationAgent:
    name="TestGenerationAgent"

    def __init__(self, ctx, logger):
        self.ctx=ctx
        self.logger=logger

    def run(self):
        contracts=self.ctx.state.get("contracts",[])
        inferred=self.ctx.state.get("inferredSchemas",[])

        components={"schemas":{}}
        for s in inferred:
            components["schemas"][s["name"]]=s["schema"]

        paths={}
        data_refs={}
        env = [
            {"key":"baseUrl","value":"http://localhost:3000","type":"default"},
            {"key":"authToken","value":"","type":"secret"},
        ]

        for c in contracts:
            op={
                "summary": f"{c['method']} {c['path']}",
                "description": f"Generated from `{c.get('file')}` line `{c.get('line')}`",
                "parameters": self.openapi_params(c.get("parameters", [])),
                "responses":{
                    "200":{
                        "description":"OK",
                        "content":{"application/json":{"schema": c.get("responseBody") or {"type":"object"}}}
                    },
                    "400":{"description":"Bad Request"},
                    "401":{"description":"Unauthorized"},
                    "422":{"description":"Validation Error"}
                },
                "x-qaira-source": {"file": c.get("file"), "line": c.get("line"), "confidence": c.get("confidence")}
            }

            rb=c.get("requestBody")
            if rb:
                schema_name=rb.get("schemaRef")
                if schema_name:
                    schema={"$ref":"#/components/schemas/"+schema_name}
                else:
                    schema=rb
                op["requestBody"]={
                    "required": c["method"] in BODY_METHODS,
                    "content":{"application/json":{"schema":schema,"example":self.example_body(rb)}}
                }
                data_refs[c["id"]] = self.example_body(rb)

            paths.setdefault(c["path"],{})[c["method"].lower()]=op

        openapi={
            "openapi":"3.0.0",
            "info":{
                "title":"Generated API Contract",
                "version":"1.0.0",
                "description":"Generated by QAira semantic compiler from source-code analysis."
            },
            "servers":[{"url":"{{baseUrl}}","description":"Configured base URL"}],
            "paths":paths,
            "components":components
        }
        self.ctx.write_json("generated/openapi.json",openapi)
        self.ctx.write_json("generated/data_references.json", data_refs)
        self.ctx.write_json("generated/environment.postman_environment.json", {
            "name":"Generated API Environment",
            "values":env
        })

        postman_items=[]
        negative_items=[]
        edge_items=[]

        for c in contracts:
            item=self.postman_item(c, data_refs.get(c["id"], {}), test_type="positive")
            postman_items.append(item)

            rb=c.get("requestBody") or {}
            props=rb.get("properties") or {}
            required=set(rb.get("required") or [])

            for req in sorted(required):
                neg_body={k:v for k,v in data_refs.get(c["id"], {}).items() if k!=req}
                negative_items.append(self.postman_item(c, neg_body, test_type="negative_missing_required", missing_field=req))

            if props and c["method"] in BODY_METHODS:
                edge_body={k:self.edge_value(k) for k in props.keys()}
                edge_items.append(self.postman_item(c, edge_body, test_type="edge_empty_values"))

        self.ctx.write_json("generated/postman_collection.json",self.collection("Generated API Collection",postman_items))
        self.ctx.write_json("generated/negative_tests.postman_collection.json",self.collection("Generated Negative API Tests",negative_items))
        self.ctx.write_json("generated/edge_tests.postman_collection.json",self.collection("Generated Edge API Tests",edge_items))
        self.ctx.write_text("generated/curl_requests.sh","\n".join([f"curl -X {c['method']} \"$BASE_URL{c['path']}\"" for c in contracts])+"\n")
        self.ctx.write_json("generated/qaira_tests.json",{"tests":postman_items,"negativeTests":negative_items,"edgeTests":edge_items})
        self.ctx.write_json("final/final_test_generation_report.json",{
            "generated":["openapi","postman","negative_postman","edge_postman","curl","qaira","data_references","environment"],
            "contractCount":len(contracts),
            "negativeTests":len(negative_items),
            "edgeTests":len(edge_items),
            "componentSchemas":len(components["schemas"]),
            "dataReferenceRoutes":len(data_refs)
        })
        return AgentResult(self.name,"success",0.95 if contracts else 0,{"generated":8,"contracts":len(contracts),"negativeTests":len(negative_items),"edgeTests":len(edge_items)}, {})

    def openapi_params(self, params):
        out=[]
        for p in params:
            out.append({
                "name":p.get("name"),
                "in":p.get("in"),
                "required": bool(p.get("required", p.get("in")=="path")),
                "schema":{"type":p.get("type","string")},
                "description":f"Generated {p.get('in')} parameter"
            })
        return out

    def collection(self, name, items):
        return {
            "info":{"name":name,"schema":"https://schema.getpostman.com/json/collection/v2.1.0/collection.json"},
            "variable":[{"key":"baseUrl","value":"{{baseUrl}}"},{"key":"authToken","value":"{{authToken}}"}],
            "item":items
        }

    def postman_item(self, c, body_obj, test_type="positive", missing_field=None):
        expected = [200,201,204] if test_type=="positive" else [400,401,422]
        scripts = [
            f"pm.test('status is expected for {test_type}', function () {{ pm.expect({json.dumps(expected)}).to.include(pm.response.code); }});",
            "let jsonData = {}; try { jsonData = pm.response.json(); } catch(e) {}",
            "pm.test('response time acceptable', function () { pm.expect(pm.response.responseTime).to.be.below(5000); });"
        ]
        if test_type == "positive":
            scripts.append("pm.test('response body is object or empty success', function () { pm.expect(['object','undefined']).to.include(typeof jsonData); });")
            scripts.append("if (jsonData && jsonData.id) { pm.collectionVariables.set('lastId', jsonData.id); }")
            scripts.append("if (jsonData && jsonData.token) { pm.collectionVariables.set('authToken', jsonData.token); }")
        if missing_field:
            scripts.append(f"pm.test('validation should complain about missing {missing_field}', function () {{ pm.expect(pm.response.code).to.be.oneOf([400,422]); }});")

        req={
            "method":c["method"],
            "header":[
                {"key":"Content-Type","value":"application/json"},
                {"key":"Authorization","value":"Bearer {{authToken}}","disabled":False}
            ],
            "url":"{{baseUrl}}"+c["path"]
        }
        if body_obj:
            req["body"]={"mode":"raw","raw":json.dumps(body_obj, indent=2)}
        return {
            "name":f"{test_type.upper()} {c['method']} {c['path']}",
            "request":req,
            "event":[{"listen":"test","script":{"type":"text/javascript","exec":scripts}}],
            "description":f"Source: {c.get('file')}:{c.get('line')}"
        }

    def example_body(self, rb):
        return {k:self.example_value(k) for k in (rb.get("properties") or {}).keys()}

    def example_value(self, name):
        n=name.lower()
        if "email" in n: return "{{data.email}}"
        if "password" in n: return "{{data.password}}"
        if n.endswith("id") or n=="id": return "{{lastId}}"
        if n.startswith("is") or n.startswith("has"): return True
        if "count" in n or "page" in n or "limit" in n: return 1
        return "{{data."+name+"}}"

    def edge_value(self, name):
        n=name.lower()
        if n.startswith("is") or n.startswith("has"): return False
        if "count" in n or "page" in n or "limit" in n: return 0
        return ""
